blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/alex2276564/SmartSpawnPoint#readme
    about: Check out the documentation for installation and usage guide